apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-webapp
  labels:
    app: wp-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-webapp
  template:
    metadata:
      labels:
        app: wp-webapp
    spec:
      containers:
      - name: wp-webapp
        image: wpacrmain001.azurecr.io/webapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10 