apiVersion: v1
kind: Service
metadata:
  name: wp-webapp
  labels:
    app: wp-webapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: wp-webapp 