apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
data:
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-mongodb
type: Opaque
stringData:
  connection-string: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@wp-cosmos-main-001.mongo.cosmos.azure.com:10255/wp-db?ssl=true&replicaSet=globaldb" 