apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
data:
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-mongodb
type: Opaque
stringData:
  connection-string: "" 