apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-api
  labels:
    app: wp-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-api
  template:
    metadata:
      labels:
        app: wp-api
    spec:
      containers:
      - name: wp-api
        image: wpacrmain001.azurecr.io/api:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: wp-mongodb
              key: connection-string
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 10 