apiVersion: v1
kind: Service
metadata:
  name: wp-api
  labels:
    app: wp-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: wp-api